name: coverage
on: push
permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Go test coverage
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: "stable"
      - run: go test -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
