name: coverage
on: push
permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Go test coverage
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "stable"
      - run: go test -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
