name: test
on: push
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.22"
          - "1.23"
          - "1.24"
          - "1.25"
          - "1.26"
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race .
